import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Spinnaker } from "next/font/google";
import { Dancing_Script } from "next/font/google";
import { Patrick_Hand } from "next/font/google";
import { Architects_Daughter } from "next/font/google";
import "./globals.css";

const spinnaker = Spinnaker({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-spinnaker",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-dancing-script",
});

const architectsDaughter = Architects_Daughter({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-architects_daughter",
});

const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-patrick-hand",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spinnaker.variable} ${dancingScript.variable} ${patrickHand.variable} ${architectsDaughter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
